# [build]
#   publish = "public"
#   command = "mkdir -p public/efert && gridsome build && cp -R dist/* public/efert"
# 
# [[redirects]]
# from = "/"
# to = "/efert"

[build]
  publish = "dist"
  command = "gridsome build"